---

- include: configure_control_service.yml
  when: "'{{ flocker_control_service_groupname }}' in group_names"

- include: configure_agent.yml
  when: "'{{ flocker_agents_groupname }}'  in group_names"

- include: configure_agent.yml
  when: "'{{ flocker_client_groupname }}'  in group_names"

- include: configure_client.yml
  when: "'{{ flocker_client_groupname }}'  in group_names"

