apiVersion: v1
kind: Service
metadata:
  name: sbt
  labels:
    app: sbt
spec:
  ports:
  - port: 7077
    name: master-port
  clusterIP: None
  selector:
    app: sbt
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sbt
spec:
  serviceName: sbt
  replicas: 1
  template:
    metadata:
      labels:
        app: sbt
    spec:
      containers:
      - name: sbt
        imagePullPolicy: Always
        image: dckreg:5000/sbt
        command:
        - sh
        - -c
        - sleep 100000
