app_group: analytics/spark
docker_image: zeppelin
instances: 1
tag: 0.6.1 
cpus: 0.1 
mem: 1024

network: HOST

volumes: |
    {
        "containerPath": "/usr/local/zeppelin/notebook",
        "hostPath": "/usr/local/zeppelin/notebook",
        "mode": "RW"
    }
     
parameters: |
    { "key": "log-driver", "value": "syslog" },
    { "key": "log-opt", "value": "tag={{ app_id }}" }


constraints: UNIQUE

forcePullImage: false
