---

- name: Install jq
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - jq
    - curl

- name: Create DOCKER_REGISTRY env variable
  lineinfile:
      dest=/etc/bash.bashrc
      line="export DOCKER_REGISTRY={{ groups['docker_registry'][0] }}:5000"
      state=present

