---

- name: add analytic user
  command: sudo useradd analytics -u 9000 -d /home/analytics  -m  creates=/home/analytics

- name: Creates directory /data/dfs dir for hdfs
  file: path={{ item.path }} state=directory owner=analytics
  with_items:
    - { path: '/data/dfs' }
  when: "'hdfs_nn' in group_names or 'hdfs_dn' in group_names or 'hdfs_cli' in group_names"

- name: Creates spark directory
  file: path={{ item.path }} state=directory owner=analytics
  with_items:
    - { path: '/data/spark' }
  when: "'spark_master' in group_names or 'spark_worker' in group_names"

- name: Creates kafka
  file: path={{ item.path }} state=directory owner=analytics
  with_items:
    - { path: '/data/kafka-logs' }
  when: "'kafka' in group_names "

