apiVersion: v1
kind: Service
metadata:
  name: dn
  labels:
    app: dn
spec:
  ports:
  - port: 50075
    name: datanodeweb 
  - port: 50010
    name: datatrnsfr
  - port: 50020
    name: metadata
  clusterIP: None
  selector:
    app: dn
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dn
spec:
  serviceName: dn
  replicas: 2
  template:
    metadata:
      labels:
        app: dn
    spec:
      containers:
      - name: dn
        imagePullPolicy: Always
        image: dckreg:5000/hdfs:2.7
        ports:
        - containerPort: 50075
          name: datanodeweb
        - containerPort: 50010
          name: datatrnsfr
        - containerPort: 50020
          name: metadata
        command:
        - sh
        - -c
        - datanode.sh
        volumeMounts:
        - name: datadir
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
