apiVersion: v1
kind: Service
metadata:
  name: dfsrs
  labels:
    app: dfsrs
spec:
  ports:
  - port: 16020
    name: rs-port 
  - port: 16030
    name: rs-info-port
  clusterIP: None
  selector:
    app: dfsrs
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dfsrs
spec:
  serviceName: dfsrs
  replicas: 2
  template:
    metadata:
      labels:
        app: dfsrs
    spec:
      containers:
      - name: rs
        imagePullPolicy: Always
        image: dckreg:5000/hbase:1.2.4
        ports:
        - containerPort: 16020
          name: rs-port
        - containerPort: 16030
          name: rs-info-port
        env:
        - name: MODE
          value: "worker"
        - name: ZK_LIST
          value: "{{ zk_list }}"
        command:
        - sh
        - -c
        - starthbase.sh
