apiVersion: v1
kind: Service
metadata:
  name: sprkwrk
  labels:
    app: spkrwrk
spec:
  ports:
  - port: 8081
    name: webui 
  clusterIP: None
  selector:
    app: sprkwrk
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sprkwrk
spec:
  serviceName: sprkwrk
  replicas: 2
  template:
    metadata:
      labels:
        app: sprkwrk
    spec:
      containers:
      - name: sprkwrk
        imagePullPolicy: Always
        image: dckreg:5000/spark:2.1.0
        ports:
        - containerPort: 8081
          name: webui
        command:
        - sh
        - -c
        - startspark.sh
        env:
        - name: MODE
          value: "worker"
        - name: SPARK_MASTER_IP
          value: "sprkmstr-0.sprkmstr"
        - name: SPARK_LOCAL_DIRS
          value: "/data/spark/data"
        - name: SPARK_WORKER_DIR
          value: "/data/spark/work"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        - name: SPARK_DAEMON_JAVA_OPTS
          value: "-Dspark.deploy.recoveryMode=FILESYSTEM -Dspark.deploy.recoveryDirectory=/data/spark/recovery"
        volumeMounts:
        - name: datadir
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
