apiVersion: v1
kind: Service
metadata:
  name: sprkmstr
  labels:
    app: sprkmstr
spec:
  ports:
  - port: 7077
    name: master-port 
  - port: 8080
    name: master-ui
  clusterIP: None
  selector:
    app: sprkmstr
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sprkmstr
spec:
  serviceName: sprkmstr
  replicas: 1
  template:
    metadata:
      labels:
        app: sprkmstr
    spec:
      containers:
      - name: sprkmstr
        imagePullPolicy: Always
        image: dckreg:5000/spark:2.1.0
        ports:
        - containerPort: 7077
          name: master-port
        - containerPort: 8080
          name: master-ui
        command:
        - sh
        - -c
        - startspark.sh
        env:
        - name: MODE
          value: "master"
        - name: SPARK_MASTER_IP
          value: "sprkmstr-0.sprkmstr"
        - name: SPARK_LOCAL_DIRS
          value: "/data/spark/data"
        - name: SPARK_WORKER_DIR
          value: "/data/spark/work"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        - name: SPARK_DAEMON_JAVA_OPTS
          value: "-Dspark.deploy.recoveryMode=FILESYSTEM -Dspark.deploy.recoveryDirectory=/data/spark/recovery"
        volumeMounts:
        - name: datadir
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
