app_group: analytics/spark
docker_image: spark
instances: 1
tag: 2.0 
cpus: 0.1 
mem: 256

network: HOST

volumes: |
    {
        "containerPath": "/data/spark/",
        "hostPath": "/data/spark/",
        "mode": "RW"
    }
     
     
parameters: |
    { "key": "env", "value": "MODE=master" },
    { "key": "env", "value": "SPARK_MASTER_IP=sm1" },
    { "key": "env", "value": "SPARK_LOCAL_DIRS=/data/spark/data" },
    { "key": "env", "value": "SPARK_WORKER_DIR=/data/spark/work" },
    { "key": "env", "value": "SPARK_MASTER_WEBUI_PORT=8090" },
    { "key": "env", "value": "SPARK_WORKER_MEMORY=1024m" },
    { "key": "env", "value": "SPARK_DAEMON_JAVA_OPTS=-Dspark.deploy.recoveryMode=FILESYSTEM -Dspark.deploy.recoveryDirectory=/data/spark/recovery" },
    {{ logging }}


constraints: UNIQUE

