---
- hosts: mgmt
  become: yes
  roles:
     - common
     - docker-new
     - kube-sslcer
     - kube
     - grafana
     - log_server

- hosts: etcd
  become: yes
  roles:
     - etcd
  tags:
     -  etcd

- hosts: master
  become: yes
  roles:
     - common
     - docker-new
     - kube
     - kube-master

- hosts: node
  become: yes
  roles:
     - common
     - docker-new
     - kube
     - kube-node

- hosts: docker_registry
  become: yes
  roles:
     - docker_registry
