---
- hosts: mgmt
  become: yes
  roles:
     - common
     - docker-new
     - kube-sslcer
     - kube
     - grafana
     - log_server
     - flocker-new 

- hosts: etcd
  become: yes
  roles:
     - etcd
  tags:
     -  etcd

- hosts: master
  become: yes
  roles:
     - common
     - docker-new
     - kube
     - kube-master
     - flocker-new 

- hosts: node
  become: yes
  roles:
     - common
     - docker-new
     - kube
     - kube-node
     - flocker-new 

- hosts: docker_registry
  become: yes
  roles:
     - docker-new
     - docker_registry
