apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: {{ kafka_replicas }}
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: dckreg:5000/kafka:0.10.0.1
        ports:
        - containerPort: 9092
          name: server
        env:
        - name: ZK
          value: "{{ zk_list }}"
        - name: NUM_PARTITIONS
          value: "{{ kafka_replicas }}"
        command: 
        - sh
        - -c
        - kafka-start.sh
        volumeMounts:
        - name: datadir
          mountPath: /data/kafka-logs
  volumeClaimTemplates:
  - metadata:
      name: datadir
      {{ pv_annotations }} 	
         {{ pv_annotations_line }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ kafka_disk }}
