kind: PersistentVolume
apiVersion: v1
metadata:
  name: kaf0001
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kafka-0"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kaf0002
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kafka-1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kaf0003
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kafka-2"
