---

- name: Create hdfs alias
  lineinfile:
      dest=/etc/bash.bashrc
      line="alias hdfs='sudo docker  run -it --net=host  -u hdfs -v /tmp/data:/tmp/data dckreg:5000/{{ docker_image}}:{{ tag }}  /bin/bash'"
      state=present
  when: "'hdfs_cli' in  group_names and ansible_os_family == 'Debian'"

- name: Create spark shell Debian
  lineinfile:
      dest=/etc/bash.bashrc
      line="alias spark-shell='sudo docker run -u spark -w /home/spark -it  -e SPARK_LOCAL_IP={{ inventory_hostname }}  --net=host dckreg:5000/{{ docker_image}}:{{ tag }} spark-shell --master spark://sm1:7077'"
  when: "'spark_shell' in  group_names and ansible_os_family == 'Debian'"

- name: Create spark spark cli Debian
  lineinfile:
      dest=/etc/bash.bashrc
      line="alias spark-shell='sudo docker run -u spark -w /home/spark -it -v /tmp/data:/tmp/data -e SPARK_LOCAL_IP={{ inventory_hostname }}  --net=host dckreg:5000/{{ docker_image}}:{{ tag }}  /bin/bash'"
  when: "'spark' in  group_names and ansible_os_family == 'Debian'"

- name: Create spark shell Radhat
  lineinfile:
      dest=/etc/bashrc
      line="alias spark-shell='sudo docker run -u spark -w /home/spark -it  -e SPARK_LOCAL_IP={{ inventory_hostname }}  --net=host dckreg:5000/{{ docker_image}}:{{ tag }} spark-shell --master spark://sm1:7077'"
  when: "'spark_shell' in  group_names and ansible_os_family == 'Radhat'"

- name: Create hbase client
  lineinfile:
      dest=/etc/bash.bashrc
      line="alias hbase='sudo docker run -u hbase  -w /home/hbase -it  --net=host dckreg:5000/{{ docker_image}}:{{ tag }} /bin/bash'"
  when: "'hbase_cli' in  group_names and ansible_os_family == 'Debian'"

- name: Create hbase client
  lineinfile:
      dest=/etc/bashrc
      line="alias hbase='sudo docker run -u hbase  -w /home/hbase -it  --net=host dckreg:5000/{{ docker_image}}:{{ tag }} /bin/bash'"
  when: "'hbase_cli' in  group_names and ansible_os_family == 'Radhat'"

- name: Create /user/hbase dir on hdfs
  command: docker run  --net=host dckreg:5000/hdfs:2.7 hdfs dfs -mkdir -p /user/hbase
  delegate_to: localhost
  when: "'hbase_cli' in  group_names" 

- name: change owner of /user/hbase dir on hdfs
  command: docker run  --net=host dckreg:5000/hdfs:2.7 hdfs dfs -chown hbase  /user/hbase
  delegate_to: localhost
  when: "'hbase_cli' in  group_names" 

- name:  create kafka client
  lineinfile:
      dest=/etc/bash.bashrc
      line="alias kafka='sudo docker run -u kafka  -w /home/kafka -it  --net=host dckreg:5000/{{ docker_image}}:{{ tag }} /bin/bash'"
  when: "'kafka_cli' in  group_names and ansible_os_family == 'Debian'"

- name:  create kafka client
  lineinfile:
      dest=/etc/bashrc
      line="alias kafka='sudo docker run -u kafka  -w /home/kafka -it  --net=host dckreg:5000/{{ docker_image}}:{{ tag }} /bin/bash'"
  when: "'kafka_cli' in  group_names and ansible_os_family == 'Redhat'"
