app_group: analytics/spark
docker_image: spark-master
instances: 1
tag: 2.0 
cpus: 0.1 
mem: 512

network: HOST

volumes: |
    {
        "containerPath": "/usr/local/spark/conf",
        "hostPath": "/etc/spark",
        "mode": "RW"
    },
    {
        "containerPath": "/opt/spark/",
        "hostPath": "/opt/spark/",
        "mode": "RW"
    }
     
     
parameters: |
    { "key": "env", "value": "SPARK_MASTER_IP={{ inventory_hostname }}" },
    { "key": "log-driver", "value": "syslog" },
    { "key": "log-opt", "value": "tag=hdfs-nn" }


constraints: UNIQUE

spark_master_webui_port: 8090
spark_worker_memory: 1024m
spark_local_dirs: /opt/spark/data
spark_daemon_java_opts: "-Dspark.deploy.recoveryMode=FILESYSTEM -Dspark.deploy.recoveryDirectory=/opt/spark/recovery"
spark_worker_dir: /opt/spark/work
