apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka-headless
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: dckreg:5000/kafka:0.10.0.1
        ports:
        - containerPort: 9092
          name: server
        env:
        - name: ZK
          value: "zk-0.zk-headless:2181,zk-1.zk-headless:2181,zk-2.zk-headless:2181"
        - name: NUM_PARTITIONS
          value: "3"
        command: 
        - sh
        - -c
        - kafka-start.sh
        volumeMounts:
        - name: datadir
          mountPath: /data/kafka-logs
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
