kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo
  annotations:
    volume.beta.kubernetes.io/storage-class: "ssd"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
