kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2


type: io1, gp2, sc1, st1. See AWS docs for details. Default: gp2.
zone: AWS zone. If not specified, a random zone from those where Kubernetes cluster has a node is chosen.
iopsPerGB: only for io1 volumes. I/O operations per second per GiB. AWS volume plugin multiplies this with size of requested volume to compute IOPS of the volume and caps it at 20 000 IOPS (maximum supported by AWS, see AWS docs).
encrypted: denotes whether the EBS volume should be encrypted or not. Valid values are true or false.
