apiVersion: v1
kind: Service
metadata:
  name: noderest
  labels:
    app: noderest
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 32000
      protocol: TCP
      targetPort: 3000
  selector:
    app: noderest
