---

- name: ip route to find out interface 
  shell: ip route | grep {{ inventory_hostname }} | cut -d ' ' -f 3
  register: result

- name: add the route for 10.96.0.0/12
  shell: ip route add {{ service_ip_range }} dev {{ result.stdout }}
  ignore_errors: True

- name: Creates /etc/kubernetes/manifests directory
  file: path=/etc/kubernetes/manifests  recurse=yes state=directory

- name: Creates /etc/kubernetes/pki directory
  file: path={{ cert_dir }}  recurse=yes state=directory

- name: Creates /etc/systemd/system/kubelet.service.d directory
  file: path=/etc/systemd/system/kubelet.service.d recurse=yes state=directory

- name: Creates /etc/cni/net.d directory
  file: path=/etc/cni/net.d recurse=yes state=directory

- name: copy openssl certificate from ansible host
  copy: src={{ master_cert_dir }} dest={{ kube_config_dir }}

- name: Copy kube config files
  template: src="{{ item.src }}" dest="{{ item.dest }}" 
  with_items:
     - { src: 'kube-apiserver.json.j2', dest: '/etc/kubernetes/manifests/kube-apiserver.json'  }
     - { src: 'kube-controller-manager.json.j2', dest: '/etc/kubernetes/manifests/kube-controller-manager.json'  }
     - { src: 'kube-scheduler.json.j2', dest: '/etc/kubernetes/manifests/kube-scheduler.json'  }
     - { src: 'kubelet.conf.j2', dest: '/etc/kubernetes/kubelet.conf'  }
     - { src: '10-kubeadm.conf.j2', dest: '/etc/systemd/system/kubelet.service.d/10-kubeadm.conf'  }
     - { src: '10-weave.conf.j2', dest: '/etc/cni/net.d/10-weave.conf'  }
     - { src: 'admin.conf.j2', dest: '/etc/kubernetes/admin.conf'  }
  register: result
  notify: restart kubelet

- name: Ensure systemd is reloaded if any config  changed
  shell: systemctl daemon-reload
  when: result|changed
