---

- name: deploy mararthon marathon app
  uri:
    url: http://{{ groups["marathon"][0] }}:8080/v2/apps/{{ app_id }}
    method: PUT
    status_code: 200,201,204
    HEADER_Content-Type: "application/json"
    body: '{{ lookup("template", "marathon_lb.json.j2") }}'
    body_format: json
  delegate_to: localhost

