---

- name: deploy marathon lb app

  uri:
    url: http://{{ groups["marathon"][0] }}:8080/v2/apps/{{ app_id }}
    method: PUT
    status_code: 200,201,204
    HEADER_Content-Type: "application/json"
    body: '{{ lookup("file", "/var/tmp/marathon_lb.json") }}'
    body_format: json
  delegate_to: localhost
