apiVersion: v1
kind: Service
metadata:
  name: zeppelin
  labels:
    app: zeppelin
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      protocol: TCP
      targetPort: 8080
  selector:
    app: zeppelin
