apiVersion: v1
kind: Service
metadata:
  name: smcli
  labels:
    app: smcli
spec:
  ports:
  - port: 7077
    name: master-port 
  - port: 8080
    name: master-ui
  clusterIP: None
  selector:
    app: smcli
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: smcli
spec:
  serviceName: smcli
  replicas: 1
  template:
    metadata:
      labels:
        app: smcli
    spec:
      containers:
      - name: smcli
        imagePullPolicy: Always
        image: dckreg:5000/spark:{{ spark_version }}
        ports:
        - containerPort: 7077
          name: master-port
        - containerPort: 8080
          name: master-ui
        command:
        - sh
        - -c
        - sleep 10000
