kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk-0
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/zk-0"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/zk-1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/zk-2"
