apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeppelin-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zeppelin
    spec:
      containers:
      - name: zeppelin
        imagePullPolicy: Always
        image: dckreg:5000/zeppelin:0.7.0
        ports:
        - containerPort: 8080
