app_group: analytics/hadoop
docker_image: hdfs
tag: 2.7 
cpus: 0.1 
mem: 128
instances: 1

constraints: UNIQUE

network: HOST

volumes: |
     {
        "containerPath": "/data/dfs",
        "hostPath": "/data/dfs",
        "mode": "RW"
     }

parameters: |
     { "key": "env", "value": "MODE=dn" },
     { "key": "env", "value": "NN_IP=nn1" },
     {{ logging }}
